version: "3"

networks:
    stdcourse:
services:
    app:
        build:
            context: ./docker
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - stdcourse

    mysql:
        image: mysql:8
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: db

        networks:
            - stdcourse

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: rootpass

        networks:
            - stdcourse

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - ./redis_data:/data
        networks:
            - stdcourse

volumes:
    mysql_data:
    redis_data:
